dist: jammy
language: java

jdk:
  - openjdk17

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm

install: skip

before_install:
  - nvm install 20
  - nvm use 20
  - node --version
  - npm --version
  - java -version
  - mvn -version

script:
  - cd $TRAVIS_BUILD_DIR/registro-autos/backend && mvn clean package -DskipTests
  - cd $TRAVIS_BUILD_DIR/registro-autos/frontend && npm ci && npm run build
