name: Pruebas de Integracion Continua

on:
  push:
    branches: [ main ]

jobs:
  verificar-conexion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Levantar los contenedores de Docker
        run: docker compose up -d

      - name: Esperar a que los contenedores arranquen
        # Esto le da tiempo a la red interna de Docker para estabilizarse
        run: sleep 10

      - name: Ejecutar prueba de comunicacion (Ping)
        run: docker exec contenedor_dos ping -c 4 app_servidor